const states = [
	{key: "AL", display: "Alabama"},
	{key: "AK", display: "Alaska"},
	{key: "AZ", display: "Arizona"},
	{key: "AR", display: "Arkansas"},
	{key: "CA", display: "California"},
	{key: "CO", display: "Colorado"},
	{key: "CT", display: "Connecticut"},
	{key: "DE", display: "Delaware"},
	{key: "DC", display: "District of Columbia"},
	{key: "FL", display: "Florida"},
	{key: "GA", display: "Georgia"},
	{key: "HI", display: "Hawaii"},
	{key: "ID", display: "Idaho"},
	{key: "IL", display: "Illinois"},
	{key: "IN", display: "Indiana"},
	{key: "IA", display: "Iowa"},
	{key: "KS", display: "Kansas"},
	{key: "KY", display: "Kentucky"},
	{key: "LA", display: "Louisiana"},
	{key: "ME", display: "Maine"},
	{key: "MD", display: "Maryland"},
	{key: "MA", display: "Massachusetts"},
	{key: "MI", display: "Michigan"},
	{key: "MN", display: "Minnesota"},
	{key: "MS", display: "Mississippi"},
	{key: "MO", display: "Missouri"},
	{key: "MT", display: "Montana"},
	{key: "NE", display: "Nebraska"},
	{key: "NV", display: "Nevada"},
	{key: "NH", display: "New Hampshire"},
	{key: "NJ", display: "New Jersey"},
	{key: "NM", display: "New Mexico"},
	{key: "NY", display: "New York"},
	{key: "NC", display: "North Carolina"},
	{key: "ND", display: "North Dakota"},
	{key: "OH", display: "Ohio"},
	{key: "OK", display: "Oklahoma"},
	{key: "OR", display: "Oregon"},
	{key: "PA", display: "Pennsylvania"},
	{key: "RI", display: "Rhode Island"},
	{key: "SC", display: "South Carolina"},
	{key: "SD", display: "South Dakota"},
	{key: "TN", display: "Tennessee"},
	{key: "TX", display: "Texas"},
	{key: "UT", display: "Utah"},
	{key: "VT", display: "Vermont"},
	{key: "VA", display: "Virginia"},
	{key: "WA", display: "Washington"},
	{key: "WV", display: "West Virginia"},
	{key: "WI", display: "Wisconsin"},
	{key: "WY", display: "Wyoming"}
];

export default states